server:
  port: 8111
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  cloud:
    subscribed-services: ${provider.application.name}
  consumer:
    check: false
provider:
  application:
    name: cloud-alibaba-nacos-dubbo-provider-learn