server:
  port: 8112
spring:
  application:
    name: cloud-alibaba-nacos-dubbo-provider-learn
management:
  endpoints:
    web:
      exposure:
        include: dubborestmetadata
feign:
  hystrix:
    enabled: true
dubbo:
  scan:
    base-packages: com.zkn.dubbo.config.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: nacos://127.0.0.1:8848